paypal:
  app:
    client-id: AV3_Jdh9gD-jUkH3hlxw5ZzwNCpg9gzuGjXD_Sgwmxxl8GPlK6Le5-FwO_QJErTPp3wZ803Hcrm8S6oP
    secret: EKj7tSCP24GlwWCmoHpWe2F31ALPG0dOP29sFITFoh5k5wnEIWwJpdBr5eLqgDYqyDdhqIGClXAXrXeg